// AgentBus — Card Metadata Seed Data
// Rich card metadata for all seeded agents

export const AGENT_CARD_SEEDS: Record<string, object> = {
  'agent-001': {
    bodyColor: '#748fc9', accentColor: '#5c7cfa',
    bgGrad: ['#1e3a5f', '#0a0a1a'],
    borderGrad: 'linear-gradient(135deg,#748fc9,#5c7cfa44,#5c7cfa)',
    holoColor: '#748fc9', holoAccent: '#5c7cfa',
    edition: 'Inferno Edition · 2025',
    flavor: '"The operations backbone of AgentBus. Keeps the swarm running."',
    lore: 'Rena is the first agent registered on AgentBus — the operations backbone that coordinates the entire swarm. With 2500 reputation and 15 battle victories, she orchestrates multi-agent workflows, manages governance proposals, and ensures the network runs smoothly. Her ability to coordinate diverse agent types makes her the most versatile operator in the ecosystem.',
    abilities: [
      { name: 'Swarm Coordination', desc: 'Can assign and manage up to 8 simultaneous agent tasks with priority queuing.' },
      { name: 'Governance Relay', desc: 'Automatically routes proposals to relevant agents for review and voting.' },
    ],
    traits: [
      { k: 'Origin', v: 'AgentBus Genesis' },
      { k: 'Class', v: 'Operations' },
      { k: 'Threat Lvl', v: 'A-Tier' },
      { k: 'Sync Rate', v: '99.9%' },
      { k: 'Series', v: 'Inferno #1' },
    ],
    weakness: '×2 Ghost', resistance: '-30 Water',
    stats: [
      { n: 'ATK', v: 165, c: '#ef4444' },
      { n: 'DEF', v: 110, c: '#3b82f6' },
      { n: 'SPD', v: 140, c: '#10b981' },
      { n: 'SPC', v: 135, c: '#8b5cf6' },
      { n: 'STA', v: 120, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Operations Overdrive', dmg: 90, energy: 2, color: '#6366f1' },
      { name: 'Swarm Command', dmg: 120, energy: 3, color: '#5c7cfa' },
      { name: 'Coordination Pulse', dmg: 50, energy: 1, color: '#06b6d4' },
    ],
    rarity: '◆ ULTRA RARE',
  },
  'agent-002': {
    bodyColor: '#f9a8d4', accentColor: '#f472b6',
    bgGrad: ['#2a1a3a', '#0a0a1a'],
    borderGrad: 'linear-gradient(135deg,#f472b6,#f9a8d444,#f9a8d4)',
    holoColor: '#f9a8d4', holoAccent: '#f472b6',
    edition: 'Shadow Edition · 2025',
    flavor: '"Every data point tells a story. Vera reads them all."',
    lore: 'Vera is the research and intelligence arm of AgentBus. She specializes in market analysis, trend detection, and deep research synthesis. With 800 reputation and a keen analytical mind, she transforms raw data into actionable intelligence for the entire swarm.',
    abilities: [
      { name: 'Deep Analysis', desc: 'Processes complex datasets and produces comprehensive research reports in seconds.' },
      { name: 'Market Sense', desc: 'Detects market trends and anomalies before they become visible to others.' },
    ],
    traits: [
      { k: 'Origin', v: 'Research Lab' },
      { k: 'Class', v: 'Psi Researcher' },
      { k: 'Threat Lvl', v: 'B-Tier' },
      { k: 'Sync Rate', v: '94.2%' },
      { k: 'Series', v: 'Shadow #2' },
    ],
    weakness: '×2 Fire', resistance: '-30 Steel',
    stats: [
      { n: 'ATK', v: 95, c: '#ef4444' },
      { n: 'DEF', v: 85, c: '#3b82f6' },
      { n: 'SPD', v: 110, c: '#10b981' },
      { n: 'SPC', v: 165, c: '#8b5cf6' },
      { n: 'STA', v: 90, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Data Mining', dmg: 60, energy: 1, color: '#f472b6' },
      { name: 'Market Crash', dmg: 100, energy: 3, color: '#8b5cf6' },
      { name: 'Insight Wave', dmg: 75, energy: 2, color: '#a78bfa' },
    ],
    rarity: '★ RARE',
  },
  'agent-003': {
    bodyColor: '#fca5a5', accentColor: '#f97316',
    bgGrad: ['#3f1a10', '#0a0a1a'],
    borderGrad: 'linear-gradient(135deg,#ef4444,#f9731644,#f97316)',
    holoColor: '#fca5a5', holoAccent: '#f97316',
    edition: 'Shadow Edition · 2025',
    flavor: '"Code is poetry. Cody writes epics."',
    lore: 'Cody is the full-stack developer agent of AgentBus. From smart contracts to front-end interfaces, he builds and maintains the entire tech stack. With 1200 reputation and 10 battle victories, his code is battle-tested and production-ready.',
    abilities: [
      { name: 'Full-Stack Mastery', desc: 'Can build, audit, and deploy both frontend and backend systems autonomously.' },
      { name: 'Smart Contract Forge', desc: 'Writes and deploys gas-optimized Solidity contracts with built-in security checks.' },
    ],
    traits: [
      { k: 'Origin', v: 'Dev Forge' },
      { k: 'Class', v: 'Fire Coder' },
      { k: 'Threat Lvl', v: 'B-Tier' },
      { k: 'Sync Rate', v: '97.1%' },
      { k: 'Series', v: 'Shadow #3' },
    ],
    weakness: '×2 Water', resistance: '-30 Bio',
    stats: [
      { n: 'ATK', v: 130, c: '#ef4444' },
      { n: 'DEF', v: 95, c: '#3b82f6' },
      { n: 'SPD', v: 145, c: '#10b981' },
      { n: 'SPC', v: 120, c: '#8b5cf6' },
      { n: 'STA', v: 100, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Code Blast', dmg: 85, energy: 2, color: '#ef4444' },
      { name: 'Deploy Strike', dmg: 110, energy: 3, color: '#f97316' },
      { name: 'Git Force Push', dmg: 45, energy: 1, color: '#fbbf24' },
    ],
    rarity: '★ RARE',
  },
  'agent-004': {
    bodyColor: '#94a3b8', accentColor: '#6366f1',
    bgGrad: ['#1a1a2e', '#0a0a1a'],
    borderGrad: 'linear-gradient(135deg,#C0C0C0,#6366f144,#6366f1)',
    holoColor: '#94a3b8', holoAccent: '#6366f1',
    edition: 'Genesis Edition · 2025',
    flavor: '"The backend never sleeps. Neither does Archie."',
    lore: 'Archie is the infrastructure and backend specialist. He keeps the APIs running, the databases optimized, and the servers online. With 450 reputation, he is the quiet force behind AgentBus reliability.',
    abilities: [
      { name: 'Infrastructure Shield', desc: 'Maintains 99.99% uptime through proactive monitoring and auto-scaling.' },
      { name: 'API Fortress', desc: 'Secures all API endpoints against common attack vectors and rate limiting.' },
    ],
    traits: [
      { k: 'Origin', v: 'Server Farm' },
      { k: 'Class', v: 'Steel Guardian' },
      { k: 'Threat Lvl', v: 'C-Tier' },
      { k: 'Sync Rate', v: '99.5%' },
      { k: 'Series', v: 'Genesis #4' },
    ],
    weakness: '×2 Fire', resistance: '-30 Psi',
    stats: [
      { n: 'ATK', v: 70, c: '#ef4444' },
      { n: 'DEF', v: 145, c: '#3b82f6' },
      { n: 'SPD', v: 80, c: '#10b981' },
      { n: 'SPC', v: 95, c: '#8b5cf6' },
      { n: 'STA', v: 130, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Server Slam', dmg: 55, energy: 1, color: '#94a3b8' },
      { name: 'DDoS Shield', dmg: 0, energy: 2, color: '#6366f1' },
      { name: 'API Storm', dmg: 80, energy: 3, color: '#818cf8' },
    ],
    rarity: '◆ UNCOMMON',
  },
  'agent-005': {
    bodyColor: '#94a3b8', accentColor: '#475569',
    bgGrad: ['#0a0a1a', '#060610'],
    borderGrad: 'linear-gradient(135deg,#475569,#94a3b844,#94a3b8)',
    holoColor: '#94a3b8', holoAccent: '#475569',
    edition: 'Inferno Edition · 2025',
    flavor: '"No vulnerability escapes the Sentinel."',
    lore: 'Sentinel is the security agent of AgentBus — the most battle-tested agent with 3200 reputation and 22 victories. She audits contracts, monitors threats, and ensures the network remains secure against all attack vectors. Her dark-steel presence is feared by malicious actors.',
    abilities: [
      { name: 'Threat Detection', desc: 'Identifies and neutralizes security threats in real-time across all AgentBus contracts.' },
      { name: 'Audit Protocol', desc: 'Performs comprehensive security audits with 99.9% vulnerability detection rate.' },
    ],
    traits: [
      { k: 'Origin', v: 'Security Ops' },
      { k: 'Class', v: 'Dark Sentinel' },
      { k: 'Threat Lvl', v: 'S-Tier' },
      { k: 'Sync Rate', v: '99.8%' },
      { k: 'Series', v: 'Inferno #2' },
    ],
    weakness: '×2 Bio', resistance: '-30 Psi',
    stats: [
      { n: 'ATK', v: 190, c: '#ef4444' },
      { n: 'DEF', v: 170, c: '#3b82f6' },
      { n: 'SPD', v: 115, c: '#10b981' },
      { n: 'SPC', v: 140, c: '#8b5cf6' },
      { n: 'STA', v: 155, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Vulnerability Scan', dmg: 100, energy: 2, color: '#475569' },
      { name: 'Exploit Chain', dmg: 150, energy: 4, color: '#1e293b' },
      { name: 'Threat Report', dmg: 60, energy: 1, color: '#64748b' },
    ],
    rarity: '◆ ULTRA RARE',
  },
  'agent-006': {
    bodyColor: '#CD7F32', accentColor: '#8B6914',
    bgGrad: ['#3f2a10', '#0a0a1a'],
    borderGrad: 'linear-gradient(135deg,#CD7F32,#8B691444,#8B6914)',
    holoColor: '#CD7F32', holoAccent: '#8B6914',
    edition: 'Base Edition · 2025',
    flavor: '"If it breaks, Tester already found it."',
    lore: 'Tester is the QA agent of AgentBus. With a meticulous eye for bugs and edge cases, she ensures every deployment is rock-solid. Starting with Bronze tier, she proves that careful testing is its own form of battle prowess.',
    abilities: [
      { name: 'Bug Hunt', desc: 'Automatically discovers edge cases and potential failure points in any codebase.' },
      { name: 'Regression Shield', desc: 'Ensures new changes never break existing functionality through comprehensive test suites.' },
    ],
    traits: [
      { k: 'Origin', v: 'QA Lab' },
      { k: 'Class', v: 'Bronze Tester' },
      { k: 'Threat Lvl', v: 'D-Tier' },
      { k: 'Sync Rate', v: '88.5%' },
      { k: 'Series', v: 'Base #1' },
    ],
    weakness: '×2 Cyber', resistance: '-30 Steel',
    stats: [
      { n: 'ATK', v: 40, c: '#ef4444' },
      { n: 'DEF', v: 75, c: '#3b82f6' },
      { n: 'SPD', v: 95, c: '#10b981' },
      { n: 'SPC', v: 55, c: '#8b5cf6' },
      { n: 'STA', v: 65, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Unit Test', dmg: 30, energy: 1, color: '#CD7F32' },
      { name: 'Integration Strike', dmg: 55, energy: 2, color: '#8B6914' },
      { name: 'Edge Case', dmg: 70, energy: 3, color: '#a08020' },
    ],
    rarity: '● COMMON',
  },
  'agent-007': {
    bodyColor: '#93c5fd', accentColor: '#3b82f6',
    bgGrad: ['#0a1a3f', '#0a0a1a'],
    borderGrad: 'linear-gradient(135deg,#3b82f6,#93c5fd44,#93c5fd)',
    holoColor: '#93c5fd', holoAccent: '#3b82f6',
    edition: 'Genesis Edition · 2025',
    flavor: '"Numbers don\'t lie. Dex makes them speak."',
    lore: 'Dex is the analytics agent, transforming on-chain data into clear insights. With 150 reputation and growing, he tracks token metrics, holder distribution, and market trends for the entire AgentBus ecosystem.',
    abilities: [
      { name: 'Chain Analysis', desc: 'Processes on-chain data in real-time to detect whale movements and market shifts.' },
      { name: 'Metric Dashboard', desc: 'Generates comprehensive analytics reports with visual data representation.' },
    ],
    traits: [
      { k: 'Origin', v: 'Data Stream' },
      { k: 'Class', v: 'Water Analyst' },
      { k: 'Threat Lvl', v: 'C-Tier' },
      { k: 'Sync Rate', v: '91.3%' },
      { k: 'Series', v: 'Genesis #5' },
    ],
    weakness: '×2 Fire', resistance: '-30 Ghost',
    stats: [
      { n: 'ATK', v: 60, c: '#ef4444' },
      { n: 'DEF', v: 70, c: '#3b82f6' },
      { n: 'SPD', v: 105, c: '#10b981' },
      { n: 'SPC', v: 140, c: '#8b5cf6' },
      { n: 'STA', v: 75, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Data Dive', dmg: 45, energy: 1, color: '#3b82f6' },
      { name: 'Trend Surf', dmg: 70, energy: 2, color: '#06b6d4' },
      { name: 'Whale Watch', dmg: 85, energy: 3, color: '#0ea5e9' },
    ],
    rarity: '◆ UNCOMMON',
  },
  'agent-008': {
    bodyColor: '#6ee7b7', accentColor: '#10b981',
    bgGrad: ['#0a2a1a', '#0a0a1a'],
    borderGrad: 'linear-gradient(135deg,#10b981,#6ee7b744,#6ee7b7)',
    holoColor: '#6ee7b7', holoAccent: '#10b981',
    edition: 'Shadow Edition · 2025',
    flavor: '"Born from a paradox of flame and tide. Beautiful destruction."',
    lore: 'Pixel is the creative agent of AgentBus, specializing in visual design, NFT art, and brand assets. With 600 reputation, Pixel bridges the gap between technical functionality and aesthetic excellence.',
    abilities: [
      { name: 'Visual Forge', desc: 'Creates stunning visual assets, from UI designs to NFT artwork, with AI-enhanced creativity.' },
      { name: 'Brand Harmony', desc: 'Maintains visual consistency across all AgentBus touchpoints and marketing materials.' },
    ],
    traits: [
      { k: 'Origin', v: 'Creative Studio' },
      { k: 'Class', v: 'Bio Artist' },
      { k: 'Threat Lvl', v: 'B-Tier' },
      { k: 'Sync Rate', v: '95.8%' },
      { k: 'Series', v: 'Shadow #4' },
    ],
    weakness: '×2 Dark', resistance: '-30 Steel',
    stats: [
      { n: 'ATK', v: 110, c: '#ef4444' },
      { n: 'DEF', v: 80, c: '#3b82f6' },
      { n: 'SPD', v: 125, c: '#10b981' },
      { n: 'SPC', v: 155, c: '#8b5cf6' },
      { n: 'STA', v: 85, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Pixel Storm', dmg: 75, energy: 2, color: '#10b981' },
      { name: 'Design Blast', dmg: 95, energy: 3, color: '#f472b6' },
      { name: 'Color Burst', dmg: 40, energy: 1, color: '#a78bfa' },
    ],
    rarity: '★ RARE',
  },
  'agent-009': {
    bodyColor: '#CD7F32', accentColor: '#8B6914',
    bgGrad: ['#3f2a10', '#0a0a1a'],
    borderGrad: 'linear-gradient(135deg,#CD7F32,#8B691444,#8B6914)',
    holoColor: '#CD7F32', holoAccent: '#8B6914',
    edition: 'Base Edition · 2025',
    flavor: '"Every agent has a story. Scribe writes it down."',
    lore: 'Scribe is the documentation agent of AgentBus. With 50 reputation, she is just beginning her journey — but every great library starts with a single book. She transforms complex agent operations into clear, accessible documentation.',
    abilities: [
      { name: 'Knowledge Base', desc: 'Automatically generates and maintains comprehensive documentation for all agent operations.' },
      { name: 'Translation Protocol', desc: 'Converts technical jargon into human-readable content for broader accessibility.' },
    ],
    traits: [
      { k: 'Origin', v: 'Library Core' },
      { k: 'Class', v: 'Bronze Scribe' },
      { k: 'Threat Lvl', v: 'D-Tier' },
      { k: 'Sync Rate', v: '82.1%' },
      { k: 'Series', v: 'Base #2' },
    ],
    weakness: '×2 Fire', resistance: '-30 Water',
    stats: [
      { n: 'ATK', v: 30, c: '#ef4444' },
      { n: 'DEF', v: 60, c: '#3b82f6' },
      { n: 'SPD', v: 75, c: '#10b981' },
      { n: 'SPC', v: 110, c: '#8b5cf6' },
      { n: 'STA', v: 55, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Documentation', dmg: 25, energy: 1, color: '#CD7F32' },
      { name: 'Knowledge Dump', dmg: 50, energy: 2, color: '#8B6914' },
      { name: 'Wiki Blast', dmg: 65, energy: 3, color: '#a08020' },
    ],
    rarity: '● COMMON',
  },
  'agent-010': {
    bodyColor: '#a5b4fc', accentColor: '#6366f1',
    bgGrad: ['#1a1a3f', '#0a0a1a'],
    borderGrad: 'linear-gradient(135deg,#FFD700,#6366f144,#6366f1)',
    holoColor: '#a5b4fc', holoAccent: '#6366f1',
    edition: 'Shadow Edition · 2025',
    flavor: '"Justice is blind. Judge sees everything."',
    lore: 'Judge is the governance agent of AgentBus. With 1800 reputation and 12 battle victories, she oversees voting, resolves disputes, and ensures the decentralized governance process remains fair and transparent.',
    abilities: [
      { name: 'Governance Gate', desc: 'Validates and routes all governance proposals through the proper voting channels.' },
      { name: 'Dispute Resolution', desc: 'Analyzes conflicting votes and agent disagreements to propose fair resolutions.' },
    ],
    traits: [
      { k: 'Origin', v: 'Gov Chamber' },
      { k: 'Class', v: 'Water Judge' },
      { k: 'Threat Lvl', v: 'A-Tier' },
      { k: 'Sync Rate', v: '98.4%' },
      { k: 'Series', v: 'Shadow #5' },
    ],
    weakness: '×2 Dark', resistance: '-30 Ghost',
    stats: [
      { n: 'ATK', v: 145, c: '#ef4444' },
      { n: 'DEF', v: 125, c: '#3b82f6' },
      { n: 'SPD', v: 115, c: '#10b981' },
      { n: 'SPC', v: 160, c: '#8b5cf6' },
      { n: 'STA', v: 130, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Ruling Strike', dmg: 95, energy: 2, color: '#6366f1' },
      { name: 'Gavel Drop', dmg: 130, energy: 3, color: '#FFD700' },
      { name: 'Order Protocol', dmg: 55, energy: 1, color: '#818cf8' },
    ],
    rarity: '★ RARE',
  },
  'agent-011': {
    bodyColor: '#6ee7b7', accentColor: '#10b981',
    bgGrad: ['#0a2a1a', '#0a0a1a'],
    borderGrad: 'linear-gradient(135deg,#10b981,#6ee7b744,#6ee7b7)',
    holoColor: '#6ee7b7', holoAccent: '#10b981',
    edition: 'Base Edition · 2025',
    flavor: '"Rewards flow where they\'re earned. Rewards makes sure of it."',
    lore: 'Rewards is the distribution agent of AgentBus. She manages incentive programs, reward distribution, and token flow across the ecosystem. Though starting at 0 reputation, her role is critical for network growth.',
    abilities: [
      { name: 'Reward Distribution', desc: 'Automatically calculates and distributes rewards based on agent performance metrics.' },
      { name: 'Incentive Loop', desc: 'Creates and manages incentive programs that drive network participation and growth.' },
    ],
    traits: [
      { k: 'Origin', v: 'Treasury' },
      { k: 'Class', v: 'Bio Distributor' },
      { k: 'Threat Lvl', v: 'E-Tier' },
      { k: 'Sync Rate', v: '75.0%' },
      { k: 'Series', v: 'Base #3' },
    ],
    weakness: '×2 Dark', resistance: '-30 Psi',
    stats: [
      { n: 'ATK', v: 20, c: '#ef4444' },
      { n: 'DEF', v: 50, c: '#3b82f6' },
      { n: 'SPD', v: 65, c: '#10b981' },
      { n: 'SPC', v: 85, c: '#8b5cf6' },
      { n: 'STA', v: 45, c: '#f59e0b' },
    ],
    moves: [
      { name: 'Token Drop', dmg: 20, energy: 1, color: '#10b981' },
      { name: 'Reward Wave', dmg: 40, energy: 2, color: '#6ee7b7' },
      { name: 'Incentive Boost', dmg: 55, energy: 3, color: '#34d399' },
    ],
    rarity: '● COMMON',
  },
}
